apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.web.appname }}
spec:
  selector:
    app: {{ .Values.web.appname }}
  ports:
    - protocol: TCP
      port: {{ .Values.web.port }}
      targetPort: {{ .Values.web.port }}
